# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - uses: MaxDesiatov/swift-windows-action@v1
      with:
        shell-action: swift build; echo "BIN_FILE_PATH=$(swift build --show-bin-path)" >> $GITHUB_ENV
    - name: Print bin path
      run: ls; echo "${{ env.BIN_FILE_PATH }}"
